config/routes.rb
Rails.application.routes.draw do
devise_for :users
  get "loadings/index"
  

  authenticated :user do
    root "loadings#index", as: "authenticated_root"
  end

  resources :loadings do
    resources :approved_trucks 
  end

  resources :trucks
  
  root "welcome#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/approved_truck.rb
class ApprovedTruck < ApplicationRecord
  belongs_to :loading
end

app/models/loading.rb
class Loading < ApplicationRecord
	belongs_to :user
	has_many :approved_trucks
end

app/models/role.rb
class Role < ApplicationRecord
	has_many :users
end

app/models/truck.rb
class Truck < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :loadings
  belongs_to :role
  has_many :trucks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.permit(:sign_up) do |user_params|
	  	user_params.permit(:role_id, :company_name, :email, :password, :password_confirmation)
	  end
	  devise_parameter_sanitizer.permit(:account_update) do |user_params|
	  	user_params.permit(:role_id, :company_name, :email, :password, :password_confirmation, :current_password)
	  end
	end
end

app/controllers/approved_trucks_controller.rb
class ApprovedTrucksController < ApplicationController
	before_action :authenticate_user!
	def create
		@loading = Loading.find(params[:loading_id])
		@approved_truck = ApprovedTruck.create(params[:approved_truck].permit(:trucks_sent))
		@approved_truck.user_id = current_user.id
		@approved_truck.user_company_name = current_user.company_name
		@approved_truck.loading_id = @loading.id

		if @approved_truck.save
			redirect_to loading_path(@loading)
		else
			render 'new'
		end
	end

end

app/controllers/loadings_controller.rb
class LoadingsController < ApplicationController

	before_action :find_loading, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	before_action :is_signed_in?


	def is_signed_in?
	   if !user_signed_in?
	      redirect_to new_user_session_path
	   end
	end


	def index
		if current_user.role_id==1
			@loadings = Loading.where(user_id: current_user)
		else
			@loadings = Loading.all.order("created_at DESC")
		end
	end

	def show
		@approved_trucks = ApprovedTruck.where(loading_id: @loading)
	end

	def new
		if current_user.role_id==1
			@loading = current_user.loadings.build
		else
			redirect_to root_path
		end
	end

	def create
		if current_user.role_id==1
			@loading = current_user.loadings.build(loading_params)

			if @loading.save
				redirect_to @loading
			else
				render 'new'
			end
		else
			redirect_to root_path
		end
	end

	def edit
	end

	def update
		if current_user.role_id==1
			if @loading.update(loading_params)
				redirect_to @loading
			else
				render 'edit'
			end
		else
			redirect_to root_path
		end
	end

	def destroy
		if current_user.role_id==1
			@loading.destroy
			redirect_to root_path
		else
			redirect_to root_path
		end
	end

	private

	def find_loading
		@loading = Loading.find(params[:id])
	end

	def loading_params
		params.require(:loading).permit(:from, :to, :weight, :goods_type, :number_of_trucks, :date_of_loading)
	end

end

app/controllers/trucks_controller.rb
class TrucksController < ApplicationController
	before_action :find_truck, only: [:show, :edit, :update, :destroy]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		if current_user.role_id==2
			@trucks = Truck.where(user_id: current_user)
		else
			redirect_to root_path
		end
	end

	def show

	end

	def new
		if current_user.role_id==2
			@truck = current_user.trucks.build
		else
			redirect_to root_path
		end
	end
	
	def create
		if current_user.role_id==2
			@truck = current_user.trucks.build(truck_params)

			if @truck.save
				redirect_to @truck
			else
				render 'new'
			end
		else
			redirect_to root_path
		end
	end

	def edit
	end

	def update
		if current_user.role_id==2
			if @truck.update(truck_params)
				redirect_to @truck
			else
				render 'edit'
			end
		else
			redirect_to root_path	
		end
	end

	def destroy
		if current_user.role_id==2
			@truck.destroy
			redirect_to trucks_path
		else
			redirect_to root_path
		end
	end

	private

	def find_truck
		@truck = Truck.find(params[:id])
	end

	def truck_params
		params.require(:truck).permit(:truck_number)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/approved_trucks_helper.rb
module ApprovedTrucksHelper
end

app/helpers/loadings_helper.rb
module LoadingsHelper
end

app/helpers/trucks_comings_helper.rb
module TrucksComingsHelper
end

app/helpers/trucks_helper.rb
module TrucksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/approved_trucks/_approved_truck.html.erb
<p><%= approved_truck.user_company_name %><%= approved_truck.trucks_sent %></p>

app/views/approved_trucks/_form.html.erb
<%= simple_form_for([@loading, @loading.approved_trucks.build]) do |f| %>
<%= f.collection_select :trucks_sent, current_user.trucks.all, :truck_number, :truck_number %>
<%= f.submit "Add" %>
<% end %>

app/views/loadings/edit.html.erb
<% content_for :title do %>
  <title>Edit Loading</title>
<% end %>
  <% content_for :head do %>
    <%= stylesheet_link_tag "dashboard" %>
    <%= javascript_include_tag "dashboard" %>
  <% end %>

		<section class="hbox stretch">
			<aside class="bg-dark aside-sm" id="nav">
				<section class="vbox">
					<header class="dker nav-bar nav-bar-fixed-top">
						<a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="#nav">
							<i class="fa fa-bars"></i>
						</a>
						<a href="#" class="dker nav-brand" data-toggle="fullscreen">trolleyapp</a>
					</header>
					<section class="w-f">
						<div class="bg-success nav-user hidden-xs pos-rlt">
						 	<div class="nav-avatar pos-rlt"> 
						 		<a href="#" class="thumb-sm avatar animated rollIn" data-toggle="dropdown"> 
						 			<%= image_tag("avatar.png", :class => "") %> <span><%= current_user.company_name %></span> 
						 		</a> 
						 	</div> 
						 </div>
						<nav class="nav-primary hidden-xs">
							<ul class="nav">
								<li class="active">
									<%= link_to new_loading_path do%>  
										<i class="fa fa-plus"></i>
										<span>New Loading</span>
									<% end %>
								</li>	
								<li >
									<%= link_to loadings_path do%>  
										<i class="fa fa-eye"></i>
										<span>All Loading</span>
									<% end %>
								</li>
								<li>
									<%= link_to edit_user_registration_path do%>  
										<i class="fa fa-user"></i>
										<span>Profile</span>
									<% end %>
								</li>
								<li>
									<%= link_to destroy_user_session_path, :method=> :delete do%>  
										<i class="fa fa-sign-out"></i>
										<span>Log Out</span>
									<% end %>
								</li>					
							</ul>
						</nav>
					</section>
				</section>
			</aside>
		<section id="content">
			<section class="vbox">
				<header class="header bg-white b-b">
					<p>Welcome to Trolleyapp</p>
				</header>
				<section class="scrollable wrapper">
					<div class="row">
						<div class="col-lg-12">
							<div class="row">
								<h1>Edit Loading</h1>
								<%= render 'form' %>
							</div>		
						</div>
					</div>
				</section>
			</section>

		</section>
		</section>

app/views/loadings/index.html.erb
<% content_for :title do %>
  <title>Dashboard</title>
<% end %>
  <% content_for :head do %>
    <%= stylesheet_link_tag "dashboard" %>
    <%= javascript_include_tag "dashboard" %>
  <% end %>

		<section class="hbox stretch">
			<aside class="bg-dark aside-sm" id="nav">
				<section class="vbox">
					<header class="dker nav-bar nav-bar-fixed-top">
						<a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="#nav">
							<i class="fa fa-bars"></i>
						</a>
						<a href="#" class="dker nav-brand" data-toggle="fullscreen">trolleyapp</a>
					</header>
					<section class="w-f">
						<div class="bg-success nav-user hidden-xs pos-rlt">
						 	<div class="nav-avatar pos-rlt"> 
						 		<a href="#" class="thumb-sm avatar animated rollIn" data-toggle="dropdown"> 
						 			<%= image_tag("avatar.png", :class => "") %> <span><%= current_user.company_name %></span> 
						 		</a> 
						 	</div> 
						 </div>
						<% if current_user.role_id==1 %>
						<nav class="nav-primary hidden-xs">
							<ul class="nav">
								<li>
									<%= link_to new_loading_path do%>  
										<i class="fa fa-plus"></i>
										<span>New Loading</span>
									<% end %>
								</li>	
								<li  class="active">
									<%= link_to loadings_path do%>  
										<i class="fa fa-eye"></i>
										<span>All Loading</span>
									<% end %>
								</li>
								<li>
									<%= link_to edit_user_registration_path do%>  
										<i class="fa fa-user"></i>
										<span>Profile</span>
									<% end %>
								</li>
								<li>
									<%= link_to destroy_user_session_path, :method=> :delete do%>  
										<i class="fa fa-sign-out"></i>
										<span>Log Out</span>
									<% end %>
								</li>					
							</ul>
						</nav>
						<% end %>
						<% if current_user.role_id==2 %>
						<nav class="nav-primary hidden-xs">
							<ul class="nav">
								<li>
									<%= link_to trucks_path do%>  
										<i class="fa fa-plus"></i>
										<span>All Trucks</span>
									<% end %>
								</li>
								<li>
									<%= link_to new_truck_path do%>  
										<i class="fa fa-plus"></i>
										<span>Add New Truck</span>
									<% end %>
								</li>	
								<li  class="active">
									<%= link_to loadings_path do%>  
										<i class="fa fa-eye"></i>
										<span>All Loading</span>
									<% end %>
								</li>
								<li>
									<%= link_to edit_user_registration_path do%>  
										<i class="fa fa-user"></i>
										<span>Profile</span>
									<% end %>
								</li>
								<li>
									<%= link_to destroy_user_session_path, :method=> :delete do%>  
										<i class="fa fa-sign-out"></i>
										<span>Log Out</span>
									<% end %>
								</li>					
							</ul>
						</nav>
						<% end %>
					</section>
				</section>
			</aside>
		<section id="content">
			<section class="vbox">
				<header class="header bg-white b-b">
					<p>Welcome to Trolleyapp</p>
				</header>
				<section class="scrollable wrapper">
					<div class="row">
						<div class="col-lg-12">
							<div class="row">
							<%- @loadings.each do |loading| %>
								<div class="col-lg-4 col-sm-4">
									<%= link_to loading do %>
										<section class="panel">
											<div class="panel-body">
												<div class="clearfix m-b">
													<small class="text-muted pull-right"><%= time_ago_in_words(loading.created_at) + " ago" %></small>
													<small class="text-muted pull-left"><%= loading.user.company_name %></small>
												</div>
												    <span><h2>From: <%= loading.from %></h2><h2>To: <%= loading.to %></h2></span>
												    
												
											</div>
										</section>
									<% end %>
								</div>
								<% end %>
							</div>		
						</div>
					</div>
				</section>
			</section>

		</section>
		</section>

app/views/loadings/show.html.erb
<% content_for :title do %>
  <title>Loading</title>
<% end %>
  <% content_for :head do %>
    <%= stylesheet_link_tag "dashboard" %>
    <%= javascript_include_tag "dashboard" %>
  <% end %>

		<section class="hbox stretch">
			<aside class="bg-dark aside-sm" id="nav">
				<section class="vbox">
					<header class="dker nav-bar nav-bar-fixed-top">
						<a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="#nav">
							<i class="fa fa-bars"></i>
						</a>
						<a href="#" class="dker nav-brand" data-toggle="fullscreen">trolleyapp</a>
					</header>
					<section class="w-f">
						<div class="bg-success nav-user hidden-xs pos-rlt">
						 	<div class="nav-avatar pos-rlt"> 
						 		<a href="#" class="thumb-sm avatar animated rollIn" data-toggle="dropdown"> 
						 			<%= image_tag("avatar.png", :class => "") %> <span><%= current_user.company_name %></span> 
						 		</a> 
						 	</div> 
						 </div>
						<% if current_user.role_id==1 %>
						<nav class="nav-primary hidden-xs">
							<ul class="nav">
								<li>
									<%= link_to new_loading_path do%>  
										<i class="fa fa-plus"></i>
										<span>New Loading</span>
									<% end %>
								</li>	
								<li  class="active">
									<%= link_to loadings_path do%>  
										<i class="fa fa-eye"></i>
										<span>All Loading</span>
									<% end %>
								</li>
								<li>
									<%= link_to edit_user_registration_path do%>  
										<i class="fa fa-user"></i>
										<span>Profile</span>
									<% end %>
								</li>
								<li>
									<%= link_to destroy_user_session_path, :method=> :delete do%>  
										<i class="fa fa-sign-out"></i>
										<span>Log Out</span>
									<% end %>
								</li>					
							</ul>
						</nav>
						<% end %>
						<% if current_user.role_id==2 %>
						<nav class="nav-primary hidden-xs">
							<ul class="nav">
								<li>
									<%= link_to trucks_path do%>  
										<i class="fa fa-plus"></i>
										<span>All Trucks</span>
									<% end %>
								</li>
								<li>
									<%= link_to new_truck_path do%>  
										<i class="fa fa-plus"></i>
										<span>Add New Truck</span>
									<% end %>
								</li>	
								<li class="active">
									<%= link_to loadings_path do%>  
										<i class="fa fa-eye"></i>
										<span>All Loading</span>
									<% end %>
								</li>
								<li>
									<%= link_to edit_user_registration_path do%>  
										<i class="fa fa-user"></i>
										<span>Profile</span>
									<% end %>
								</li>
								<li>
									<%= link_to destroy_user_session_path, :method=> :delete do%>  
										<i class="fa fa-sign-out"></i>
										<span>Log Out</span>
									<% end %>
								</li>					
							</ul>
						</nav>
						<% end %>
					</section>
				</section>
			</aside>
		<section id="content">
			<section class="vbox">
				<header class="header bg-white b-b">
					<p>Welcome to Trolleyapp</p>
				</header>
				<section class="scrollable wrapper">
					<div class="row">
						<div class="col-lg-12">
							<div class="row">
								<div class="container">
									<div class="row">
										<div class="col-md-12">
											<p><%= @loading.user.company_name %></p>
											<h1>From: <%= @loading.from %></h1>
											<h1>To: <%= @loading.to %></h1>
											<h1>Weight: <%= @loading.weight %></h1>
											<h1>Goods Type: <%= @loading.goods_type %></h1>
											<h1>Total Trucks Required: <%= @loading.number_of_trucks %></h1>
											<h1>Date of loading: <%= @loading.date_of_loading %></h1>
											<% if @loading.approved_trucks!=0 && @loading.approved_trucks.count!=@loading.number_of_trucks %>
												<h1>Remaining Trucks Required: <%= @loading.number_of_trucks-@loading.approved_trucks.count %></h1>
											<% else %>
												<h1></h1>
											<% end %>
										</div>
									</div>
								</div>
								<div class="container">
									<div class="row">
										<% if @loading.approved_trucks.count==@loading.number_of_trucks %>
											 <p>This loading has recieved all the trucks</p>
											 <%= render @loading.approved_trucks %>
										<% else %>
											<h2>Approved trucks <%= @loading.approved_trucks.count %></h2>
											<% if current_user.role_id===1 %>
												<%= render @loading.approved_trucks %>
											<% else %>
												<%= render @loading.approved_trucks %>
												<%= render "approved_trucks/form" %>
											<% end %>
										<% end %>
									</div>
								</div>

								<% if current_user.role_id==1 %>
									<%= link_to "Edit",  edit_loading_path(@loading) %>
									<%= link_to "Delete",  loading_path(@loading), method: :delete, data: {confirm:  "Are you sure?",
								  text: "You will not be able to recover this data!",
								  type: "warning",
								  showCancelButton: true,
								  confirmButtonColor: "#DD6B55",
								  confirmButtonText: "Yes, delete it!",
								  cancelButtonText: "No, cancel plx!",
								  closeOnConfirm: false,
								  closeOnCancel: false
								} %>
								<% end %>
							</div>		
						</div>
					</div>
				</section>
			</section>

		</section>
		</section>

app/views/trucks/_form.html.erb
<%= simple_form_for @truck do |f| %>
	<%= f.input :truck_number %>
	<%= f.button :submit %>
<% end %>

app/views/trucks/edit.html.erb
<% content_for :title do %>
  <title>Edit</title>
<% end %>
  <% content_for :head do %>
    <%= stylesheet_link_tag "dashboard" %>
    <%= javascript_include_tag "dashboard" %>
  <% end %>

		<section class="hbox stretch">
			<aside class="bg-dark aside-sm" id="nav">
				<section class="vbox">
					<header class="dker nav-bar nav-bar-fixed-top">
						<a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="#nav">
							<i class="fa fa-bars"></i>
						</a>
						<a href="#" class="dker nav-brand" data-toggle="fullscreen">trolleyapp</a>
					</header>
					<section class="w-f">
						<div class="bg-success nav-user hidden-xs pos-rlt">
						 	<div class="nav-avatar pos-rlt"> 
						 		<a href="#" class="thumb-sm avatar animated rollIn" data-toggle="dropdown"> 
						 			<%= image_tag("avatar.png", :class => "") %> <span><%= current_user.company_name %></span> 
						 		</a> 
						 	</div> 
						 </div>
						<% if current_user.role_id==1 %>
						<nav class="nav-primary hidden-xs">
							<ul class="nav">
								<li>
									<%= link_to new_loading_path do%>  
										<i class="fa fa-plus"></i>
										<span>New Loading</span>
									<% end %>
								</li>	
								<li  class="active">
									<%= link_to loadings_path do%>  
										<i class="fa fa-eye"></i>
										<span>All Loading</span>
									<% end %>
								</li>
								<li>
									<%= link_to edit_user_registration_path do%>  
										<i class="fa fa-user"></i>
										<span>Profile</span>
									<% end %>
								</li>
								<li>
									<%= link_to destroy_user_session_path, :method=> :delete do%>  
										<i class="fa fa-sign-out"></i>
										<span>Log Out</span>
									<% end %>
								</li>					
							</ul>
						</nav>
						<% end %>
						<% if current_user.role_id==2 %>
						<nav class="nav-primary hidden-xs">
							<ul class="nav">
								<li>
									<%= link_to trucks_path do%>  
										<i class="fa fa-plus"></i>
										<span>All Trucks</span>
									<% end %>
								</li>
								<li class="active">
									<%= link_to new_truck_path do%>  
										<i class="fa fa-plus"></i>
										<span>Add New Truck</span>
									<% end %>
								</li>	
								<li>
									<%= link_to loadings_path do%>  
										<i class="fa fa-eye"></i>
										<span>All Loading</span>
									<% end %>
								</li>
								<li>
									<%= link_to edit_user_registration_path do%>  
										<i class="fa fa-user"></i>
										<span>Profile</span>
									<% end %>
								</li>
								<li>
									<%= link_to destroy_user_session_path, :method=> :delete do%>  
										<i class="fa fa-sign-out"></i>
										<span>Log Out</span>
									<% end %>
								</li>					
							</ul>
						</nav>
						<% end %>
					</section>
				</section>
			</aside>
		<section id="content">
			<section class="vbox">
				<header class="header bg-white b-b">
					<p>Edit your truck details</p>
				</header>
				<section class="scrollable wrapper">
					<div class="row">
						<div class="col-lg-12">
							<div class="container">
								<div class="row">
								<%= render 'form' %>
							</div>
							</div>		
						</div>
					</div>
				</section>
			</section>

		</section>
		</section>

app/views/trucks/index.html.erb
<% content_for :title do %>
  <title>All Trucks</title>
<% end %>
  <% content_for :head do %>
    <%= stylesheet_link_tag "dashboard" %>
    <%= javascript_include_tag "dashboard" %>
  <% end %>

		<section class="hbox stretch">
			<aside class="bg-dark aside-sm" id="nav">
				<section class="vbox">
					<header class="dker nav-bar nav-bar-fixed-top">
						<a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="#nav">
							<i class="fa fa-bars"></i>
						</a>
						<a href="#" class="dker nav-brand" data-toggle="fullscreen">trolleyapp</a>
					</header>
					<section class="w-f">
						<div class="bg-success nav-user hidden-xs pos-rlt">
						 	<div class="nav-avatar pos-rlt"> 
						 		<a href="#" class="thumb-sm avatar animated rollIn" data-toggle="dropdown"> 
						 			<%= image_tag("avatar.png", :class => "") %> <span><%= current_user.company_name %></span> 
						 		</a> 
						 	</div> 
						 </div>
						<% if current_user.role_id==1 %>
						<nav class="nav-primary hidden-xs">
							<ul class="nav">
								<li>
									<%= link_to new_loading_path do%>  
										<i class="fa fa-plus"></i>
										<span>New Loading</span>
									<% end %>
								</li>	
								<li  class="active">
									<%= link_to loadings_path do%>  
										<i class="fa fa-eye"></i>
										<span>All Loading</span>
									<% end %>
								</li>
								<li>
									<%= link_to edit_user_registration_path do%>  
										<i class="fa fa-user"></i>
										<span>Profile</span>
									<% end %>
								</li>
								<li>
									<%= link_to destroy_user_session_path, :method=> :delete do%>  
										<i class="fa fa-sign-out"></i>
										<span>Log Out</span>
									<% end %>
								</li>					
							</ul>
						</nav>
						<% end %>
						<% if current_user.role_id==2 %>
						<nav class="nav-primary hidden-xs">
							<ul class="nav">
								<li class="active">
									<%= link_to trucks_path do%>  
										<i class="fa fa-plus"></i>
										<span>All Trucks</span>
									<% end %>
								</li>
								<li>
									<%= link_to new_truck_path do%>  
										<i class="fa fa-plus"></i>
										<span>Add New Truck</span>
									<% end %>
								</li>	
								<li>
									<%= link_to loadings_path do%>  
										<i class="fa fa-eye"></i>
										<span>All Loading</span>
									<% end %>
								</li>
								<li>
									<%= link_to edit_user_registration_path do%>  
										<i class="fa fa-user"></i>
										<span>Profile</span>
									<% end %>
								</li>
								<li>
									<%= link_to destroy_user_session_path, :method=> :delete do%>  
										<i class="fa fa-sign-out"></i>
										<span>Log Out</span>
									<% end %>
								</li>					
							</ul>
						</nav>
						<% end %>
					</section>
				</section>
			</aside>
		<section id="content">
			<section class="vbox">
				<header class="header bg-white b-b">
					<p>You have Added <%= @trucks.count %> trucks</p>
				</header>
				<section class="scrollable wrapper">
					<div class="row">
						<div class="col-lg-12">
							<div class="row">
							<%- @trucks.each do |truck| %>								
								<%= link_to truck do %>
									<span><h2>Truck Number: <%= truck.truck_number %></h2></span>
								<% end %>										
							<% end %>
							</div>		
						</div>
					</div>
				</section>
			</section>

		</section>
		</section>

app/views/trucks/show.html.erb
<% content_for :title do %>
  <title>Truck Details</title>
<% end %>
  <% content_for :head do %>
    <%= stylesheet_link_tag "dashboard" %>
    <%= javascript_include_tag "dashboard" %>
  <% end %>

		<section class="hbox stretch">
			<aside class="bg-dark aside-sm" id="nav">
				<section class="vbox">
					<header class="dker nav-bar nav-bar-fixed-top">
						<a class="btn btn-link visible-xs" data-toggle="class:nav-off-screen" data-target="#nav">
							<i class="fa fa-bars"></i>
						</a>
						<a href="#" class="dker nav-brand" data-toggle="fullscreen">trolleyapp</a>
					</header>
					<section class="w-f">
						<div class="bg-success nav-user hidden-xs pos-rlt">
						 	<div class="nav-avatar pos-rlt"> 
						 		<a href="#" class="thumb-sm avatar animated rollIn" data-toggle="dropdown"> 
						 			<%= image_tag("avatar.png", :class => "") %> <span><%= current_user.company_name %></span> 
						 		</a> 
						 	</div> 
						 </div>
						<% if current_user.role_id==1 %>
						<nav class="nav-primary hidden-xs">
							<ul class="nav">
								<li>
									<%= link_to new_loading_path do%>  
										<i class="fa fa-plus"></i>
										<span>New Loading</span>
									<% end %>
								</li>	
								<li  class="active">
									<%= link_to loadings_path do%>  
										<i class="fa fa-eye"></i>
										<span>All Loading</span>
									<% end %>
								</li>
								<li>
									<%= link_to edit_user_registration_path do%>  
										<i class="fa fa-user"></i>
										<span>Profile</span>
									<% end %>
								</li>
								<li>
									<%= link_to destroy_user_session_path, :method=> :delete do%>  
										<i class="fa fa-sign-out"></i>
										<span>Log Out</span>
									<% end %>
								</li>					
							</ul>
						</nav>
						<% end %>
						<% if current_user.role_id==2 %>
						<nav class="nav-primary hidden-xs">
							<ul class="nav">
								<li>
									<%= link_to trucks_path do%>  
										<i class="fa fa-plus"></i>
										<span>All Trucks</span>
									<% end %>
								</li>
								<li>
									<%= link_to new_truck_path do%>  
										<i class="fa fa-plus"></i>
										<span>Add New Truck</span>
									<% end %>
								</li>	
								<li class="active">
									<%= link_to loadings_path do%>  
										<i class="fa fa-eye"></i>
										<span>All Loading</span>
									<% end %>
								</li>
								<li>
									<%= link_to edit_user_registration_path do%>  
										<i class="fa fa-user"></i>
										<span>Profile</span>
									<% end %>
								</li>
								<li>
									<%= link_to destroy_user_session_path, :method=> :delete do%>  
										<i class="fa fa-sign-out"></i>
										<span>Log Out</span>
									<% end %>
								</li>					
							</ul>
						</nav>
						<% end %>
					</section>
				</section>
			</aside>
		<section id="content">
			<section class="vbox">
				<header class="header bg-white b-b">
					<p>Welcome to Trolleyapp</p>
				</header>
				<section class="scrollable wrapper">
					<div class="row">
						<div class="col-lg-12">
							<div class="container">
								<div class="row">
									<div class="col-md-12">
										<h1>Truck Number: <%= @truck.truck_number %></h1>
									</div>
								</div>
							</div>
							<%= link_to "Edit",  edit_truck_path(@truck) %>
							<%= link_to "Delete",  truck_path(@truck), method: :delete, data: {confirm:  "Are you sure?",
								  text: "You will not be able to recover this data!",
								  type: "warning",
								  showCancelButton: true,
								  confirmButtonColor: "#DD6B55",
								  confirmButtonText: "Yes, delete it!",
								  cancelButtonText: "No, cancel plx!",
								  closeOnConfirm: false,
								  closeOnCancel: false
								} %>	
						</div>
					</div>
				</section>
			</section>

		</section>
		</section>